remote_theme: daattali/beautiful-jekyll

title: "CMPT231 16FA"
description: "Data Structures and Algorithms"
url-pretty: "cmpt231.seanho.com"

# List of links in the navigation bar
navbar-links:
  myCourses: "https://courses.mytwu.ca/course/view.php?id=33225"
  Resources:
    - Syllabus (docx): "2016-3-CMPT_231_Syllabus.docx"
    - Textbook: "http://mitpress.mit.edu/algorithms/"
    - GitHub: "https://github.com/cmpt231-16fa"
  Prof. Ho: "http://seanho.com"

# Image to show in the navigation bar - image must be a square (width = height)
avatar: "img/TreeNetwork.svg"

author:
  name: Sean Ho

social-network-links:
  rss: true
  email: "twu@seanho.com"
  github: cmpt231-16fa
  linkedin: seanho00
  facebook: seanho00

timezone: "America/Vancouver"
